export const fallbackProducts = [
  {
    id: "hammer",
    slug: "martelo-unha-27mm-cabo-fibra",
    name: "Martelo Unha 27mm Cabo Fibra",
    brand: "Catarino Prime",
    category: "Martelos",
    sku: "MT2701",
    code: "7891234567890",
    description: "Martelo profissional com cabo em fibra, cabeça polida e pegada emborrachada para uso intenso.",
    price: 49.9,
    stock: 42,
    rating: 5,
    review_count: 128,
    image_key: "hammer",
    is_featured: true,
    is_kit: false,
    specs: ["Cabeça em aço carbono", "Cabo de fibra emborrachado", "Balanceamento profissional"],
  },
  {
    id: "screwdrivers",
    slug: "jogo-de-chaves-de-fenda-6-pecas",
    name: "Jogo de Chaves de Fenda 6 Peças",
    brand: "Catarino Prime",
    category: "Chaves",
    sku: "CV0602",
    code: "7891234567891",
    description: "Kit com seis chaves de fenda para manutenção doméstica e profissional.",
    price: 59.9,
    stock: 38,
    rating: 5,
    review_count: 96,
    image_key: "screwdrivers",
    is_featured: true,
    is_kit: false,
    specs: ["Pontas imantadas", "Cabos anatômicos", "Aço cromo vanádio"],
  },
  {
    id: "pliers",
    slug: "alicate-universal-8-isolado",
    name: 'Alicate Universal 8" Isolado',
    brand: "Catarino Prime",
    category: "Alicates",
    sku: "AL0803",
    code: "7891234567894",
    description: "Alicate universal com isolamento e corte preciso para trabalhos elétricos e mecânicos.",
    price: 39.9,
    stock: 31,
    rating: 5,
    review_count: 87,
    image_key: "pliers",
    is_featured: true,
    is_kit: false,
    specs: ["Isolamento de segurança", "Corte lateral reforçado", "Pegada ergonômica"],
  },
  {
    id: "wrench",
    slug: "chave-ajustavel-10-profissional",
    name: 'Chave Ajustável 10" Profissional',
    brand: "Catarino Prime",
    category: "Chaves",
    sku: "CA1004",
    code: "7891234567895",
    description: "Chave ajustável profissional com abertura precisa e acabamento resistente.",
    price: 64.9,
    stock: 26,
    rating: 5,
    review_count: 74,
    image_key: "wrench",
    is_featured: true,
    is_kit: false,
    specs: ["Abertura milimétrica", "Acabamento fosfatizado", "Uso profissional"],
  },
  {
    id: "tape",
    slug: "trena-emborrachada-5m-x-19mm",
    name: "Trena Emborrachada 5m x 19mm",
    brand: "Catarino Prime",
    category: "Medição",
    sku: "TR0505",
    code: "7891234567892",
    description: "Trena compacta de 5 metros com caixa emborrachada e trava de lâmina.",
    price: 29.9,
    stock: 60,
    rating: 5,
    review_count: 112,
    image_key: "tape",
    is_featured: true,
    is_kit: false,
    specs: ["Lâmina de 19mm", "Trava lateral", "Caixa emborrachada"],
  },
  {
    id: "sockets",
    slug: "jogo-de-soquetes-40-pecas-com-catraca",
    name: "Jogo de Soquetes 40 Peças com Catraca",
    brand: "Catarino Prime",
    category: "Kits",
    sku: "SQ4006",
    code: "7891234567896",
    description: "Jogo completo de soquetes com catraca e maleta organizadora.",
    price: 299.9,
    stock: 18,
    rating: 5,
    review_count: 65,
    image_key: "sockets",
    is_featured: true,
    is_kit: false,
    specs: ["40 peças", "Catraca reversível", "Maleta rígida"],
  },
  {
    id: "drill",
    slug: "furadeira-de-impacto-650w",
    name: "Furadeira de Impacto 650W",
    brand: "Catarino Prime",
    category: "Ferramentas Elétricas",
    sku: "FP650I",
    code: "7891234567893",
    description:
      "A Furadeira de Impacto 650W Catarino Prime combina potência, eficiência e durabilidade para facilitar qualquer tipo de trabalho. Seu motor de alta performance oferece perfurações rápidas e precisas em diferentes materiais, enquanto o design ergonômico garante mais conforto e controle durante o uso.",
    price: 259.9,
    stock: 22,
    rating: 5,
    review_count: 128,
    image_key: "drill",
    is_featured: false,
    is_kit: false,
    specs: [
      "Potência: 650W",
      "Impactos por minuto: 0 - 48.000 ipm",
      "Rotação: 0 - 2.800 rpm",
      "Mandril de 13mm com chave",
      "Função impacto com e sem impacto",
      "Cabo de 2 metros",
    ],
  },
  {
    id: "kit110",
    slug: "kit-ferramentas-110-pecas",
    name: "Kit Ferramentas 110 Peças",
    brand: "Catarino Prime",
    category: "Kits",
    sku: "KT1107",
    code: "7891234567897",
    description: "Kit completo para qualquer desafio, com peças organizadas em maleta reforçada.",
    price: 259.9,
    stock: 15,
    rating: 5,
    review_count: 44,
    image_key: "kit110",
    is_featured: false,
    is_kit: true,
    specs: ["110 peças", "Maleta organizadora", "Uso residencial e profissional"],
  },
  {
    id: "kit85",
    slug: "kit-manutencao-85-pecas",
    name: "Kit Manutenção 85 Peças",
    brand: "Catarino Prime",
    category: "Kits",
    sku: "KT8508",
    code: "7891234567898",
    description: "Kit ideal para manutenção residencial e profissional com peças essenciais.",
    price: 189.9,
    stock: 20,
    rating: 5,
    review_count: 52,
    image_key: "kit85",
    is_featured: false,
    is_kit: true,
    specs: ["85 peças", "Chaves e soquetes", "Organização compacta"],
  },
  {
    id: "kit150",
    slug: "kit-oficina-150-pecas",
    name: "Kit Oficina 150 Peças",
    brand: "Catarino Prime",
    category: "Kits",
    sku: "KT1509",
    code: "7891234567899",
    description: "Kit de oficina com performance e organização para rotinas exigentes.",
    price: 349.9,
    stock: 12,
    rating: 5,
    review_count: 37,
    image_key: "kit150",
    is_featured: false,
    is_kit: true,
    specs: ["150 peças", "Soquetes, pontas e chaves", "Maleta rígida"],
  },
];

const productImages = {
  hammer: ["/products/hammer.jpg", "/products/kit110.svg", "/products/wrench.svg"],
  screwdrivers: ["/products/screwdrivers.jpg", "/products/kit150.svg", "/products/sockets.svg"],
  pliers: ["/products/pliers.svg", "/products/wrench.svg", "/products/kit85.jpg"],
  wrench: ["/products/wrench.svg", "/products/pliers.svg", "/products/kit85.jpg"],
  tape: ["/products/tape.svg", "/products/hammer.jpg", "/products/kit110.svg"],
  sockets: ["/products/sockets.svg", "/products/kit85.jpg", "/products/kit150.svg"],
  drill: ["/products/drill.svg", "/products/drill-detail.svg", "/products/drill-case.svg", "/products/kit85.jpg"],
  kit110: ["/products/kit110.svg", "/products/hammer.jpg", "/products/screwdrivers.jpg"],
  kit85: ["/products/kit85.jpg", "/products/sockets.svg", "/products/pliers.svg"],
  kit150: ["/products/kit150.svg", "/products/sockets.svg", "/products/screwdrivers.jpg"],
};

fallbackProducts.forEach((product) => {
  const images = productImages[product.id] || ["/products/hammer.svg"];
  product.image_url = images[0];
  product.gallery_images = images;
});

export const fallbackCoupons = [
  {
    code: "PRIME10",
    description: "10% de desconto em ferramentas Catarino Prime",
    type: "percent",
    value: 10,
    min_total: 100,
    active: true,
  },
  {
    code: "FRETE199",
    description: "Frete grátis acima de R$199,00",
    type: "fixed",
    value: 0,
    min_total: 199,
    active: true,
  },
];
